# --> Modus Vivendi (dark)
set -gq @thm_bg "#000000"
set -gq @thm_fg "#ffffff"
set -gq @thm_blue "#2fafff"
set -gq @thm_green "#44bc44"
set -gq @thm_yellow "#d0bc00"
set -gq @thm_bg_dim "#595959"  # ANSI color8 — ikke offisiell "bg-dim", se merknad over

# --> Semantic
set -gq @cfg_bg "#{@thm_bg}"
set -gq @cfg_fg "#{@thm_fg}"
set -gq @cfg_accent "#{@thm_blue}"
set -gq @cfg_pane_title "#{@thm_green}"
set -gq @cfg_date "#{@thm_yellow}"
set -gq @cfg_window_last "#{@thm_bg_dim}"
