# --> Solarized Light
set -gq @thm_bg "#fdf6e3"    # base3
set -gq @thm_fg "#657b83"    # base00
# Monotones
set -gq @thm_base03 "#002b36"
set -gq @thm_base02 "#073642"
set -gq @thm_base01 "#586e75"
set -gq @thm_base00 "#657b83"
set -gq @thm_base0  "#839496"
set -gq @thm_base1  "#93a1a1"
set -gq @thm_base2  "#eee8d5"
set -gq @thm_base3  "#fdf6e3"
# Accents (identiske i Dark og Light)
set -gq @thm_yellow  "#b58900"
set -gq @thm_orange  "#cb4b16"
set -gq @thm_red     "#dc322f"
set -gq @thm_magenta "#d33682"
set -gq @thm_violet  "#6c71c4"
set -gq @thm_blue    "#268bd2"
set -gq @thm_cyan    "#2aa198"
set -gq @thm_green   "#859900"

# --> Semantic
set -gq @cfg_bg "#{@thm_bg}"
set -gq @cfg_fg "#{@thm_fg}"
set -gq @cfg_accent "#{@thm_blue}"
set -gq @cfg_pane_title "#{@thm_green}"
set -gq @cfg_date "#{@thm_orange}"
set -gq @cfg_window_last "#{@thm_base2}"
