# Modus Vivendi (tinted) theme
set -g status-style fg=#ffffff,bg=#0d0e1c
set -g window-status-current-style fg=#0d0e1c,bold,bg=#79a8ff
set -g window-status-last-style fg=#ffffff,bold,bg=#1d2235
set -g pane-active-border-style bg=default,fg=#79a8ff
set -g pane-border-style bg=default,fg=#61647a

# #h hostshort , #S session , #W window , #T pane name
wg_prfx=" #[fg=default,bg=#1d2235]#{?client_prefix,<Prefix>,}"  # prefix indicator widget
wg_pane=" #[fg=default,bg=#1d2235]#{=26:pane_title}"
wg_date=" #[fg=default,bg=#1d2235]%d-%b-%Y#[none]"
wg_time=" #[fg=default,bg=#1d2235]%H:%M#[none]  "
set -g status-right "${wg_prfx}${wg_pane}${wg_date}${wg_time}"
