# --> Modus Operandi (light)
set -gq @thm_bg "#ffffff"
set -gq @thm_fg "#000000"
set -gq @thm_blue "#0031a9"
set -gq @thm_green "#005e00"
set -gq @thm_yellow "#813e00"
set -gq @thm_bg_dim "#f0f0f0"

# --> Semantic
set -gqF @cfg_bg "#{@thm_bg}"
set -gqF @cfg_fg "#{@thm_fg}"
set -gqF @cfg_accent "#{@thm_blue}"
set -gqF @cfg_pane_title "#{@thm_green}"
set -gqF @cfg_date "#{@thm_yellow}"
set -gqF @cfg_window_last "#{@thm_bg_dim}"
