# --> Rosé Pine Dawn
set -gq @thm_bg "#faf4ed"
set -gq @thm_fg "#575279"
# Colors
set -gq @thm_love "#b4637a"
set -gq @thm_gold "#ea9d34"
set -gq @thm_rose "#d7827e"
set -gq @thm_pine "#286983"
set -gq @thm_foam "#56949f"
set -gq @thm_iris "#907aa9"
# Surfaces and overlays
set -gq @thm_surface "#fffaf3"
set -gq @thm_overlay "#f2e9e1"
set -gq @thm_muted "#9893a5"
set -gq @thm_subtle "#797593"
set -gq @thm_highlight_low "#f4ede8"
set -gq @thm_highlight_med "#dfdad9"
set -gq @thm_highlight_high "#cecacd"

# --> Semantic
set -gq @cfg_bg "#{@thm_bg}"
set -gq @cfg_fg "#{@thm_fg}"
set -gq @cfg_accent "#{@thm_pine}"
set -gq @cfg_pane_title "#{@thm_pine}"
set -gq @cfg_date "#{@thm_gold}"
set -gq @cfg_window_last "#{@thm_surface}"
